---
version: 0.1

phases:
    build:
        commands:
            - docker build -t docker-codebuild-sample .
    post_build:
        commands:
            - eval $(aws ecr get-login --region eu-west-1)
            - env
            - 'docker tag docker-codebuild-sample:latest 329485089133.dkr.ecr.eu-west-1.amazonaws.com/docker-codebuild-sample:$CODEBUILD_BUILD_ID'
            - docker push 329485089133.dkr.ecr.eu-west-1.amazonaws.com/docker-codebuild-sample:$CODEBUILD_BUILD_ID
artifacts:
    files:
        - 'Dockerrun.aws.json'
